/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Address: typeof import('$lib/config/contractAddress.ts').Address
  const ChainId: typeof import('$lib/config/contractAddress.ts').ChainId
  const breakpoint: typeof import('$lib/components/Breakpoint.svelte').breakpoint
}
