build:
	forge build --sizes

cp-abi:
	cp ./out/MiniDaoGovernance.sol/MiniDaoGovernance.json ../src/lib/contracts_abi/
	cp ./out/MiniDaoTimeLock.sol/MiniDaoTimeLock.json ../src/lib/contracts_abi/
	cp ./out/MiniDaoToken.sol/MiniDaoToken.json ../src/lib/contracts_abi/
	cp ./out/MiniDaoVoteBox.sol/MiniDaoVoteBox.json ../src/lib/contracts_abi/